### PR TITLE
Handle WebSocket Status Code for Span Status

### PR DESCRIPTION
**Pull request by rosspatil**
fix: #66 

### Changes in this PR:
1. Implemented a check to prevent marking the span status as a failure when the `http.status_code` is 0 for WebSocket requests.
2. Added an integration test to validate this WebSocket update.
3. Updated the span check in test by including `codes.Code` to ensure the correct status is asserted.

### CODE REVIEW

**Comment by riandyrn** [comment]
Thanks for your contribution, @rosspatil. 🎉

The code is looks good to me. 👍🏻

However, can you also add tests for this?

**Comment by rosspatil** [comment]
> Thanks for your contribution, @rosspatil. 🎉
> 
> The code is looks good to me. 👍🏻
> 
> However, can you also add tests for this?

Hey @riandyrn ,

sure, adding them

**Comment by rosspatil** [comment]
hey @riandyrn ,

I added the tests. Could you please have a look?

Thanks

**Review by riandyrn — APPROVED** [review]
LGTM. Thanks a lot, @rosspatil! 🎉🎉🎉

**Comment by riandyrn** [comment]
Oh, it looks like there is a problem with the test, @rosspatil.

Sometimes it works, but sometimes it doesn't.

Do you mind to take a look at this issue?

**Comment by rosspatil** [comment]
> Oh, it looks like there is a problem with the test, @rosspatil.
> 
> Sometimes it works, but sometimes it doesn't.
> 
> Do you mind to take a look at this issue? You can take a look at the details [here](https://github.com/riandyrn/otelchi/actions/runs/11312827785/job/31460911830?pr=67).

on it @riandyrn

**Comment by rosspatil** [comment]
Hey @riandyrn,

Could you approve the workflow again?

**Review by riandyrn — APPROVED** [review]

**Comment by riandyrn** [comment]
Thanks a lot for solving this issue on the test, @rosspatil!

**Pull request merged**
