### PR TITLE
Refactor trace header support

### PR DESCRIPTION
**Pull request by costela**
Following up from the discussion in https://github.com/riandyrn/otelchi/pull/57#issuecomment-2273279267

### CODE REVIEW

**Review by riandyrn — CHANGES_REQUESTED** [review]
Hello, @costella

Thanks for your new PR, and I'm sorry for the late review.

However, I noticed in this PR, you are trying to do several things:

1. Implement `WithTraceResponseHeaders()` option & deprecate `WithTraceIDResponseHeader`.
2. Refactor `config` by making all the properties private.
3. Refactor `sdk_test.go` by adding `t.Helper()` to several test cases.

While it is tempting to implement all of these in one go, let's only focus on implementing the first objective. This will make the review much easier and ensure we won't run into unintended consequences.

cc: @ilhamsyahids

**Comment by costela** [comment]
@riandyrn yes, that's reasonable! Just removed most the rest of the changes. Will split them into another PR for consideration.
Kept the two `t.Helper` instance that are actually called in the new test, since they are arguably part of the change. WDYT?

**Comment by costela** [comment]
Just a friendly ping, in case anyone happens to have some time for a review this week :innocent:

**Comment by costela** [comment]
the pipeline failure seems unrelated? :thinking:

**Review by ilhamsyahids — APPROVED** [review]
LGTM, thanks a lot @costela! 🔥🚀

**Comment by ilhamsyahids** [comment]
Not sure about the pipeline, let me try on different branch

**Pull request merged**
